In [1]:
import pandas as pd
import requests

In [24]:
Response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=f0dba84028dc1028e7dc83b181b93741&language=en-US&page=1') #to fetch data from link directly

In [25]:
pd.DataFrame(Response.json()['results']).sample(5)[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,40.4110,8.489,20980
7,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,35.1446,8.571,14105
11,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.4763,8.534,18613
9,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,28.3895,8.566,10175
15,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,28.4289,8.495,794

In [31]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [33]:
for i in range(1,501):
    Response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=f0dba84028dc1028e7dc83b181b93741&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(Response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [34]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,288.9823,9.366,569
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,28.2021,8.958,335
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,68.7699,8.894,2037
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,83.7172,8.727,30906
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,111.3581,8.696,3803
...,...,...,...,...,...,...,...
19995,10206,Buffy the Vampire Slayer,"Blonde, bouncy Buffy is your typical high scho...",1992-07-24,3.6128,5.600,925
19996,354287,War Machine,A rock star general bent on winning the “impos...,2017-05-26,4.8202,5.613,1252
19997,18885,3 Ninjas Kick Back,"During a championship baseball match, the thre...",1994-02-25,2.4435,5.627,328
19998,11812,The Sweetest Thing,Christina's love life is stuck in neutral. Aft...,2002-04-12,3.5174,5.609,1197
19999,1819,"You, Me and Dupree",After standing in as best man for his longtime...,2006-07-13,2.7164,5.613,1453

In [36]:
df.shape

(20000, 7)

In [37]:
df.to_csv('tmdb_movies.csv')